name: Build NuGet package

env:
  INNO_VERSION: 7.0.2
  INNO_VERSION_TAG: 7_0_2
  INNO_ARCH: x64

on: [push, pull_request]

jobs:
  build:
    name: Build package
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6
    - uses: nuget/setup-nuget@v3

    - name: Download Inno Setup installer
      run: curl -f --show-error -L -o installer.exe https://github.com/jrsoftware/issrc/releases/download/is-${{ env.INNO_VERSION_TAG }}/innosetup-${{ env.INNO_VERSION }}-${{ env.INNO_ARCH }}.exe

    - name: Install Inno Setup
      run: |
        $process = Start-Process ./installer.exe -NoNewWindow -Wait -PassThru -ArgumentList "/verysilent /allusers /dir=inst"
        if ($process.ExitCode -ne 0) {
          throw "Inno Setup installer failed with exit code $($process.ExitCode)"
        }

    - name: List installed files
      run: gci inst -Recurse -File

    - name: Build NuGet package
      run: nuget pack Tools.InnoSetup.nuspec -Verbosity detailed

    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: nuget-package
        path: "*.nupkg"


  publish:
    name: Publish release to NuGet
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: windows-latest
    needs: build
    steps:
      - name: Fetch artifact
        uses: actions/download-artifact@v8
        with:
          name: nuget-package

      - uses: nuget/setup-nuget@v3
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
          nuget-api-key-source: https://www.nuget.org/api/v2/package

      - name: Publish to NuGet
        run: nuget push *.nupkg -Source https://www.nuget.org/api/v2/package
